# Generated by Django 2.0 on 2022-10-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_adscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'adscription')},
        ),
    ]
